# Generated by Django 5.1.3 on 2025-01-30 11:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("firstapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="emp",
            name="name",
            field=models.CharField(default="", max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="emp",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
